// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {authDtos} from '../models';
import {context} from '../models';

export function Login(arg1:authDtos.LoginInputDto):Promise<authDtos.LoginResponseDto>;

export function Logout(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
