// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {dtos} from '../models';
import {context} from '../models';

export function AddSession(arg1:string,arg2:handlers.sshConnection):Promise<void>;

export function Broadcast(arg1:Array<string>,arg2:string):Promise<void>;

export function ConnectWith(arg1:dtos.SSHConnectionDto):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetSession(arg1:string):Promise<handlers.sshConnection|boolean>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Send(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
