// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {userDtos} from '../models';
import {context} from '../models';

export function Create(arg1:userDtos.CreateUserInputDto):Promise<userDtos.UserDTO>;

export function GetByID(arg1:string,arg2:number):Promise<userDtos.UserDTO>;

export function MyInfo(arg1:string):Promise<userDtos.UserDTO>;

export function Startup(arg1:context.Context):Promise<void>;

export function Update(arg1:string,arg2:number,arg3:userDtos.UpdateUserInputDto):Promise<userDtos.UserDTO>;
