// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHomeDir() {
  return window['go']['ferretShellHandlers']['LocalFileHandler']['GetHomeDir']();
}

export function ListLocalFiles(arg1) {
  return window['go']['ferretShellHandlers']['LocalFileHandler']['ListLocalFiles'](arg1);
}

export function Startup(arg1) {
  return window['go']['ferretShellHandlers']['LocalFileHandler']['Startup'](arg1);
}
