// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteLocalFile(arg1) {
  return window['go']['ferretShellHandlers']['LocalFileHandler']['DeleteLocalFile'](arg1);
}

export function DeleteLocalFiles(arg1) {
  return window['go']['ferretShellHandlers']['LocalFileHandler']['DeleteLocalFiles'](arg1);
}

export function GetHomeDir() {
  return window['go']['ferretShellHandlers']['LocalFileHandler']['GetHomeDir']();
}

export function ListLocalFiles(arg1) {
  return window['go']['ferretShellHandlers']['LocalFileHandler']['ListLocalFiles'](arg1);
}

export function RenameLocalFile(arg1, arg2) {
  return window['go']['ferretShellHandlers']['LocalFileHandler']['RenameLocalFile'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['ferretShellHandlers']['LocalFileHandler']['Startup'](arg1);
}
