// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ferretShellHandlers} from '../models';
import {context} from '../models';

export function GetHomeDir():Promise<string>;

export function ListLocalFiles(arg1:string):Promise<Array<ferretShellHandlers.LocalFileInfo>>;

export function Startup(arg1:context.Context):Promise<void>;
