// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ferretShellHandlers} from '../models';
import {ferretShellDtos} from '../models';
import {context} from '../models';

export function AddSession(arg1:string,arg2:ferretShellHandlers.sshConnection):Promise<void>;

export function Broadcast(arg1:Array<string>,arg2:string):Promise<void>;

export function ConnectSFTP(arg1:ferretShellDtos.SSHConnectionDto):Promise<string>;

export function ConnectWith(arg1:ferretShellDtos.SSHConnectionDto):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DisconnectSFTP(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetSession(arg1:string):Promise<ferretShellHandlers.sshConnection|boolean>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<ferretShellHandlers.SftpFileInfo>>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Send(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
