// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSession(arg1, arg2) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['AddSession'](arg1, arg2);
}

export function Broadcast(arg1, arg2) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['Broadcast'](arg1, arg2);
}

export function ConnectSFTP(arg1) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['ConnectSFTP'](arg1);
}

export function ConnectWith(arg1) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['ConnectWith'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['Disconnect'](arg1);
}

export function DisconnectSFTP(arg1) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['DisconnectSFTP'](arg1);
}

export function DownloadDirectory(arg1, arg2, arg3) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['DownloadDirectory'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadMultipleFiles(arg1, arg2, arg3) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['DownloadMultipleFiles'](arg1, arg2, arg3);
}

export function GetSession(arg1) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['GetSession'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['ListFiles'](arg1, arg2);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['Resize'](arg1, arg2, arg3);
}

export function Send(arg1, arg2) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['Send'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['Startup'](arg1);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['UploadFile'](arg1, arg2, arg3);
}

export function UploadMultipleFiles(arg1, arg2, arg3) {
  return window['go']['ferretShellHandlers']['SftpHandlerStruct']['UploadMultipleFiles'](arg1, arg2, arg3);
}
