// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ferretShellDtos} from '../models';
import {context} from '../models';

export function CreateSshConnection(arg1:string,arg2:ferretShellDtos.CreateSshConnectionInputDto):Promise<void>;

export function DeleteConnection(arg1:string,arg2:number):Promise<void>;

export function FindAllConnectionByUser(arg1:string,arg2:number):Promise<Array<ferretShellDtos.SshDto>>;

export function GetById(arg1:string,arg2:number):Promise<ferretShellDtos.SshDto>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateSshConnection(arg1:string,arg2:number,arg3:ferretShellDtos.CreateSshConnectionInputDto):Promise<void>;
