// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSession(arg1, arg2) {
  return window['go']['ferretShellHandlers']['TerminalHandlerStruct']['AddSession'](arg1, arg2);
}

export function Broadcast(arg1, arg2) {
  return window['go']['ferretShellHandlers']['TerminalHandlerStruct']['Broadcast'](arg1, arg2);
}

export function ConnectWith(arg1) {
  return window['go']['ferretShellHandlers']['TerminalHandlerStruct']['ConnectWith'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['ferretShellHandlers']['TerminalHandlerStruct']['Disconnect'](arg1);
}

export function GetSession(arg1) {
  return window['go']['ferretShellHandlers']['TerminalHandlerStruct']['GetSession'](arg1);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['ferretShellHandlers']['TerminalHandlerStruct']['Resize'](arg1, arg2, arg3);
}

export function Send(arg1, arg2) {
  return window['go']['ferretShellHandlers']['TerminalHandlerStruct']['Send'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['ferretShellHandlers']['TerminalHandlerStruct']['Startup'](arg1);
}
