// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDockerClient(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['AddDockerClient'](arg1);
}

export function CatchClient(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['CatchClient'](arg1);
}

export function ConnectDocker(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ConnectDocker'](arg1);
}

export function ContainerExec(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerExec'](arg1, arg2);
}

export function ContainerInspect(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerInspect'](arg1, arg2);
}

export function ContainerLogs(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerLogs'](arg1, arg2);
}

export function ContainerPause(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerPause'](arg1, arg2);
}

export function ContainerRemove(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerRemove'](arg1, arg2);
}

export function ContainerRename(arg1, arg2, arg3) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerRename'](arg1, arg2, arg3);
}

export function ContainerRestart(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerRestart'](arg1, arg2);
}

export function ContainerStart(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerStart'](arg1, arg2);
}

export function ContainerStop(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerStop'](arg1, arg2);
}

export function ContainerUnPause(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainerUnPause'](arg1, arg2);
}

export function ContainersList(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ContainersList'](arg1);
}

export function CreateContainer(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['CreateContainer'](arg1, arg2);
}

export function CreateNetwork(arg1, arg2, arg3) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['CreateNetwork'](arg1, arg2, arg3);
}

export function CreateVolume(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['CreateVolume'](arg1, arg2);
}

export function DeleteNetwork(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['DeleteNetwork'](arg1, arg2);
}

export function DeleteVolume(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['DeleteVolume'](arg1, arg2);
}

export function GetInfo(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['GetInfo'](arg1);
}

export function ImageCreate(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ImageCreate'](arg1, arg2);
}

export function ImagesList(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ImagesList'](arg1);
}

export function InspectImage(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['InspectImage'](arg1, arg2);
}

export function InspectNetwork(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['InspectNetwork'](arg1, arg2);
}

export function InspectVolume(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['InspectVolume'](arg1, arg2);
}

export function ListNetworks(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ListNetworks'](arg1);
}

export function ListVolumes(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['ListVolumes'](arg1);
}

export function PruneImages(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['PruneImages'](arg1);
}

export function PruneNetworks(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['PruneNetworks'](arg1);
}

export function RemoveImage(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['RemoveImage'](arg1, arg2);
}

export function StartContainerStats(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['StartContainerStats'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['Startup'](arg1);
}

export function StopContainerStats(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['StopContainerStats'](arg1, arg2);
}

export function StreamStats(arg1, arg2, arg3, arg4) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['StreamStats'](arg1, arg2, arg3, arg4);
}

export function TerminalClose(arg1) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['TerminalClose'](arg1);
}

export function TerminalResize(arg1, arg2, arg3, arg4) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['TerminalResize'](arg1, arg2, arg3, arg4);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['dockerHandlers']['DockerSdkHandlerStruct']['TerminalWrite'](arg1, arg2);
}
